In [2]:
import pandas as pd
import requests

In [3]:
df = pd.read_csv('data/COVID-19_Case_Surveillance_Public_Use_Data_with_Geography.csv', low_memory=False)
df.head()

/Users/lucasalibozek/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (3,18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2021-12,CA,6.0,SAN DIEGO,6073.0,18 to 49 years,Male,Black,Non-Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
1,2022-01,NY,36.0,WESTCHESTER,36119.0,65+ years,Male,NaN,NaN,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,No,NaN
2,2020-10,MN,27.0,HENNEPIN,27053.0,18 to 49 years,Female,White,Non-Hispanic/Latino,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,No,NaN
3,2021-01,NV,32.0,CLARK,32003.0,18 to 49 years,Female,Unknown,Unknown,0.0,NaN,Routine surveillance,Missing,Laboratory-confirmed case,Missing,Unknown,Unknown,No,NaN
4,2022-02,AZ,4.0,PIMA,4019.0,50 to 64 years,Female,White,Non-Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69664983 entries, 0 to 69664982
Data columns (total 19 columns):
 #   Column                           Dtype
---  ------                           -----
 0   case_month                       object
 1   res_state                        object
 2   state_fips_code                  float64
 3   res_county                       object
 4   county_fips_code                 float64
 5   age_group                        object
 6   sex                              object
 7   race                             object
 8   ethnicity                        object
 9   case_positive_specimen_interval  float64
 10  case_onset_interval              float64
 11  process                          object
 12  exposure_yn                      object
 13  current_status                   object
 14  symptom_status                   object
 15  hosp_yn                          object
 16  icu_yn                           object
 17  death_yn                         object
 18  underlying_conditions_yn         object
dtypes: float64(4), object(15)
memory usage: 9.9+ GB

In [12]:
df2 = pd.read_csv('data/co-est2021-alldata.csv', encoding='latin-1')
df2.head()

# with open('data/co-est2021-alldata.csv') as f:
#     print(f)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,...,RESIDUAL2021,GQESTIMATESBASE2020,GQESTIMATES2020,GQESTIMATES2021,RBIRTH2021,RDEATH2021,RNATURALCHG2021,RINTERNATIONALMIG2021,RDOMESTICMIG2021,RNETMIG2021
0,40,3,6,1,0,Alabama,Alabama,5024279,5024803,5039877,...,242,114572,114572,114572,11.191613,12.890226,-1.698613,0.247201,4.398749,4.645950
1,50,3,6,1,1,Alabama,Autauga County,58805,58877,59095,...,8,442,442,442,11.002611,11.545112,-0.542502,0.084766,4.017903,4.102668
2,50,3,6,1,3,Alabama,Baldwin County,231767,233140,239294,...,-82,2177,2177,2177,9.567474,12.137145,-2.569671,0.266704,28.702422,28.969126
3,50,3,6,1,5,Alabama,Barbour County,25223,25180,24964,...,1,2789,2789,2789,10.928526,15.714742,-4.786216,0.039885,-3.908743,-3.868858
4,50,3,6,1,7,Alabama,Bibb County,22293,22223,22477,...,-1,2062,2062,2062,10.111857,12.617450,-2.505593,0.089485,13.825503,13.914989

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3194 entries, 0 to 3193
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUMLEV                 3194 non-null   int64
 1   REGION                 3194 non-null   int64
 2   DIVISION               3194 non-null   int64
 3   STATE                  3194 non-null   int64
 4   COUNTY                 3194 non-null   int64
 5   STNAME                 3194 non-null   object
 6   CTYNAME                3194 non-null   object
 7   ESTIMATESBASE2020      3194 non-null   int64
 8   POPESTIMATE2020        3194 non-null   int64
 9   POPESTIMATE2021        3194 non-null   int64
 10  NPOPCHG2020            3194 non-null   int64
 11  NPOPCHG2021            3194 non-null   int64
 12  BIRTHS2020             3194 non-null   int64
 13  BIRTHS2021             3194 non-null   int64
 14  DEATHS2020             3194 non-null   int64
 15  DEATHS2021             3194 non-null   int64
 16  NATURALCHG2020         3194 non-null   int64
 17  NATURALCHG2021         3194 non-null   int64
 18  INTERNATIONALMIG2020   3194 non-null   int64
 19  INTERNATIONALMIG2021   3194 non-null   int64
 20  DOMESTICMIG2020        3194 non-null   int64
 21  DOMESTICMIG2021        3194 non-null   int64
 22  NETMIG2020             3194 non-null   int64
 23  NETMIG2021             3194 non-null   int64
 24  RESIDUAL2020           3194 non-null   int64
 25  RESIDUAL2021           3194 non-null   int64
 26  GQESTIMATESBASE2020    3194 non-null   int64
 27  GQESTIMATES2020        3194 non-null   int64
 28  GQESTIMATES2021        3194 non-null   int64
 29  RBIRTH2021             3194 non-null   float64
 30  RDEATH2021             3194 non-null   float64
 31  RNATURALCHG2021        3194 non-null   float64
 32  RINTERNATIONALMIG2021  3194 non-null   float64
 33  RDOMESTICMIG2021       3194 non-null   float64
 34  RNETMIG2021            3194 non-null   float64
dtypes: float64(6), int64(27), object(2)
memory usage: 873.5+ KB