In [1]:
import pandas as pd
import requests

In [2]:
df = pd.read_csv('data/COVID-19_Case_Surveillance_Public_Use_Data_with_Geography.csv', low_memory=False)
df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2021-12,CA,6.0,SAN DIEGO,6073.0,18 to 49 years,Male,Black,Non-Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
1,2022-01,NY,36.0,WESTCHESTER,36119.0,65+ years,Male,NaN,NaN,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,No,NaN
2,2020-10,MN,27.0,HENNEPIN,27053.0,18 to 49 years,Female,White,Non-Hispanic/Latino,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,No,NaN
3,2021-01,NV,32.0,CLARK,32003.0,18 to 49 years,Female,Unknown,Unknown,0.0,NaN,Routine surveillance,Missing,Laboratory-confirmed case,Missing,Unknown,Unknown,No,NaN
4,2022-02,AZ,4.0,PIMA,4019.0,50 to 64 years,Female,White,Non-Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69664983 entries, 0 to 69664982
Data columns (total 19 columns):
 #   Column                           Dtype
---  ------                           -----
 0   case_month                       object
 1   res_state                        object
 2   state_fips_code                  float64
 3   res_county                       object
 4   county_fips_code                 float64
 5   age_group                        object
 6   sex                              object
 7   race                             object
 8   ethnicity                        object
 9   case_positive_specimen_interval  float64
 10  case_onset_interval              float64
 11  process                          object
 12  exposure_yn                      object
 13  current_status                   object
 14  symptom_status                   object
 15  hosp_yn                          object
 16  icu_yn                           object
 17  death_yn                         object
 18  underlying_conditions_yn         object
dtypes: float64(4), object(15)
memory usage: 9.9+ GB

In [5]:
tn_df = df[df['res_state'] == "TN"]
tn_df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
43,2020-11,TN,47.0,SHELBY,47157.0,50 to 64 years,Female,White,Non-Hispanic/Latino,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
52,2021-01,TN,47.0,DAVIDSON,47037.0,65+ years,Male,White,Missing,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
98,2020-11,TN,47.0,SHELBY,47157.0,50 to 64 years,Female,White,Non-Hispanic/Latino,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
108,2021-01,TN,47.0,DAVIDSON,47037.0,65+ years,Male,White,Missing,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
154,2020-11,TN,47.0,SHELBY,47157.0,50 to 64 years,Female,White,Non-Hispanic/Latino,0.0,0.0,Missing,Missing,Probable Case,Symptomatic,Missing,Missing,Missing,NaN

In [6]:
tn_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1992915 entries, 43 to 69664981
Data columns (total 19 columns):
 #   Column                           Dtype
---  ------                           -----
 0   case_month                       object
 1   res_state                        object
 2   state_fips_code                  float64
 3   res_county                       object
 4   county_fips_code                 float64
 5   age_group                        object
 6   sex                              object
 7   race                             object
 8   ethnicity                        object
 9   case_positive_specimen_interval  float64
 10  case_onset_interval              float64
 11  process                          object
 12  exposure_yn                      object
 13  current_status                   object
 14  symptom_status                   object
 15  hosp_yn                          object
 16  icu_yn                           object
 17  death_yn                         object
 18  underlying_conditions_yn         object
dtypes: float64(4), object(15)
memory usage: 304.1+ MB

In [7]:
tn_df.to_csv("data/cdc_COVID_TN.csv")